import { getFallacyOptionFrench, replaceFallacyNamesInText } from '../data/fallacyOptionTranslations';

/**
 * Translates question text to French when language is 'fr'.
 * Used by IdSearchModal, QuizView, and IdLogView.
 * Covers question prefixes and common phrases so the full question appears in French.
 */
export const translateQuestionText = (text: string, language: string): string => {
  if (language !== 'fr') return text;

  const prefixTranslations: Record<string, string> = {
    'What is': "Qu'est-ce que c'est",
    'What is?': "Qu'est-ce que c'est ?",
    'What does': "Qu'est-ce que",
    'What do we call': 'Comment appelle-t-on',
    'What?': 'Que ?',
    'What happens when you': 'Que se passe-t-il quand vous',
    'What happens when': 'Que se passe-t-il quand',
    'What happens if': 'Que se passe-t-il si',
    'What happens with': 'Que se passe-t-il avec',
    'What happens to': "Qu'arrive-t-il à",
    'What happens here': 'Que se passe-t-il ici',
    'What happens?': 'Que se passe-t-il ?',
    'What happens': 'Que se passe-t-il',
    'Result of': 'Résultat de',
    'Output of': 'Sortie de',
    'Value of': 'Valeur de',
    'Which': 'Lequel',
    'How': 'Comment',
    'When': 'Quand',
    'Where': 'Où',
    'Why': 'Pourquoi',
    'Can': 'Peut',
    'Does': 'Est-ce que',
    'Is': 'Est',
    'Are': 'Sont',
    'Will': 'Va',
    'Would': 'Serait',
    'Should': 'Devrait',
    'If you see': 'Si vous voyez',
    'When we say': 'Quand on dit',
  };

  let translated = text;
  for (const [en, fr] of Object.entries(prefixTranslations)) {
    const pattern = new RegExp(`^${en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'i');
    if (pattern.test(translated)) {
      translated = translated.replace(pattern, fr);
    }
  }
  // "return?" in "What does X return?" → "renvoie ?"
  translated = translated.replace(/\s+return\s*\?/g, ' renvoie ?');

  // Replace common phrases in the rest of the question (so full sentence is French)
  const phraseTranslations: Array<[RegExp, string]> = [
    [/\ba terminal\b/gi, 'un terminal'],
    [/\bthe terminal\b/gi, 'le terminal'],
    [/\ba command\b/gi, 'une commande'],
    [/\bthe command\b/gi, 'la commande'],
    [/\bthe computer\b/gi, "l'ordinateur"],
    [/\ba directory\b/gi, 'un répertoire'],
    [/\bthe directory\b/gi, 'le répertoire'],
    [/\ba file\b/gi, 'un fichier'],
    [/\bthe file\b/gi, 'le fichier'],
    [/\bthe prompt\b/gi, 'l\'invite de commande'],
    [/\ba folder\b/gi, 'un dossier'],
    [/\bthe folder\b/gi, 'le dossier'],
    [/\ba path\b/gi, 'un chemin'],
    [/\bthe path\b/gi, 'le chemin'],
    [/\ba program\b/gi, 'un programme'],
    [/\bthe program\b/gi, 'le programme'],
    [/\ba window\b/gi, 'une fenêtre'],
    [/\bthe window\b/gi, 'la fenêtre'],
    [/\ba key\b/gi, 'une touche'],
    [/\bthe key\b/gi, 'la touche'],
    [/\bthe cursor\b/gi, 'le curseur'],
    [/\ba web browser\b/gi, 'un navigateur web'],
    [/\bthe place\b/gi, 'l\'endroit'],
    [/\bthe home directory\b/gi, 'le répertoire personnel'],
    [/\bthe current directory\b/gi, 'le répertoire courant'],
    [/\b'current directory'\b/g, "'répertoire courant'"],
    [/\bto list\b/gi, 'lister'],
    [/\bto navigate\b/gi, 'naviguer'],
    [/\bto run\b/gi, 'exécuter'],
    [/\bto execute\b/gi, 'exécuter'],
    [/\boutput\b/gi, 'sortie'],
    [/\binput\b/gi, 'entrée'],
    [/\ban operating system\b/gi, "un système d'exploitation"],
    [/\bthe operating system\b/gi, "le système d'exploitation"],
    [/\ba GUI\b/g, 'une interface graphique'],
    [/\bcase-sensitive\b/gi, 'sensible à la casse'],
    [/\ba typo\b/gi, 'une faute de frappe'],
    [/\ban error message\b/gi, 'un message d\'erreur'],
    [/\bthe error message\b/gi, 'le message d\'erreur'],
    [/\bsucceeded\b/gi, 'réussi'],
    [/\bfailed\b/gi, 'échoué'],
    [/\bthe keyboard\b/gi, 'le clavier'],
    [/\bthe difference between\b/gi, 'la différence entre'],
    [/\bthe text\b/gi, 'le texte'],
    [/\bthe name\b/gi, 'le nom'],
    [/\bthe screen\b/gi, 'l\'écran'],
    [/\bthe line\b/gi, 'la ligne'],
    [/\bthe next\b/gi, 'le prochain'],
    [/\bthe first\b/gi, 'le premier'],
    [/\bthe last\b/gi, 'le dernier'],
    [/\bthe same as\b/gi, 'la même chose que'],
    [/\bthe same\b/gi, 'la même chose'],
    [/\bfor example\b/gi, 'par exemple'],
    [/\bwhat does\b/gi, "qu'est-ce que"],
    [/\bwhat do\b/gi, 'que fait'],
    [/\bmean when\b/gi, 'signifie quand'],
    [/\bstand for\b/gi, 'signifie'],
    [/\bwe talk about\b/gi, 'on parle de'],
    [/\bin the context of\b/gi, 'dans le contexte de'],
    [/\bwe say\b/gi, 'on dit'],
    [/\bthat appears\b/gi, 'qui s\'affiche'],
    [/\bthat shows\b/gi, 'qui affiche'],
    [/\byou type\b/gi, 'vous tapez'],
    [/\byou typed\b/gi, 'vous avez tapé'],
    [/\bwhere you type\b/gi, 'où vous tapez'],
    [/\bwhere your typing appears\b/gi, 'où votre saisie apparaît'],
    [/\bthe computer prints\b/gi, "l'ordinateur affiche"],
    [/\bsomething went wrong\b/gi, "quelque chose s'est mal passé"],
    [/\bwithout an error\b/gi, 'sans erreur'],
    [/\bdoes not recognize\b/gi, 'ne reconnaît pas'],
    [/\bdo not recognize\b/gi, 'ne reconnaissent pas'],
    [/\bthe word you typed\b/gi, 'le mot que vous avez tapé'],
    [/\bthe command you typed\b/gi, 'la commande que vous avez tapée'],
    [/\bthe command you just typed\b/gi, 'la commande que vous venez de taper'],
    [/\byou usually press\b/gi, 'vous appuyez généralement sur'],
    [/\byou press\b/gi, 'vous appuyez sur'],
    [/\bto run the command\b/gi, 'pour exécuter la commande'],
    [/\bto tell the computer\b/gi, 'pour dire à l\'ordinateur'],
    [/\bto do what the command says\b/gi, 'pour faire ce que la commande indique'],
    [/\binstruction you type\b/gi, 'instruction que vous tapez'],
    [/\ban instruction\b/gi, 'une instruction'],
    [/\bthat can hold\b/gi, 'qui peut contenir'],
    [/\bthat can contain\b/gi, 'qui peut contenir'],
    [/\bdata saved with a name\b/gi, 'données enregistrées sous un nom'],
    [/\bsaved with a name\b/gi, 'enregistré sous un nom'],
    [/\bwith a name\b/gi, 'avec un nom'],
    [/\b(e\.g\. document, image)\b/gi, '(ex. document, image)'],
    [/\b(e\.g\. \w+)\b/gi, '(ex. $1)'],
    [/\bthe blinking line\b/gi, 'la ligne clignotante'],
    [/\bthe blinking\b/gi, 'le clignotement'],
    [/\bbefore the place where you type\b/gi, "avant l'endroit où vous tapez"],
    [/\bthat appears before\b/gi, 'qui apparaît avant'],
    [/\bthat shows where you type\b/gi, 'qui indique où vous tapez'],
    [/\bthe text that appears\b/gi, 'le texte qui s\'affiche'],
    [/\bthe title of the window\b/gi, 'le titre de la fenêtre'],
    [/\bthe mouse pointer\b/gi, 'le pointeur de la souris'],
    [/\bthe first line of text\b/gi, 'la première ligne de texte'],
    [/\bright now\b/gi, 'en ce moment'],
    [/\byou are in\b/gi, 'vous êtes dans'],
    [/\byou are\b/gi, 'vous êtes'],
    [/\byour personal folder\b/gi, 'votre dossier personnel'],
    [/\byour documents and files\b/gi, 'vos documents et fichiers'],
    [/\bthe main folder\b/gi, 'le dossier principal'],
    [/\bthe desktop\b/gi, 'le bureau'],
    [/\ba temporary folder\b/gi, 'un dossier temporaire'],
    [/\bto show the names of\b/gi, 'afficher les noms de'],
    [/\bto show\b/gi, 'afficher'],
    [/\bto move from one folder to another\b/gi, 'passer d\'un dossier à un autre'],
    [/\bto move from\b/gi, 'passer de'],
    [/\bto delete\b/gi, 'supprimer'],
    [/\bto copy\b/gi, 'copier'],
    [/\bto create\b/gi, 'créer'],
    [/\bto rename\b/gi, 'renommer'],
    [/\bthe location of\b/gi, 'l\'emplacement de'],
    [/\bwhich folders it is inside\b/gi, 'dans quels dossiers il se trouve'],
    [/\bthe menu bar\b/gi, 'la barre de menus'],
    [/\bthe taskbar\b/gi, 'la barre des tâches'],
    [/\bthe command line\b/gi, 'la ligne de commande'],
    [/\bor terminal\b/gi, 'ou terminal'],
    [/\btyped as a command\b/gi, 'tapé comme commande'],
    [/\bNo\b(?!\w)/g, 'Non'],
    [/\bYes\b(?!\w)/g, 'Oui'],
    [/\bOnly on Windows\b/gi, 'Seulement sur Windows'],
    [/\bOnly on Mac\b/gi, 'Seulement sur Mac'],
    [/\bCapital and small letters\b/gi, 'Les majuscules et les minuscules'],
    [/\bare different\b/gi, 'sont différents'],
    [/\bA vs a\b/g, 'A et a'],
    [/\bA typing mistake\b/gi, 'Une faute de frappe'],
    [/\bwrong letter or missing character\b/gi, 'mauvaise lettre ou caractère manquant'],
    [/\bText from the computer\b/gi, "Texte de l'ordinateur"],
    [/\bsaying something went wrong\b/gi, "indiquant qu'une erreur s'est produite"],
    [/\bA successful result\b/gi, 'Un résultat correct'],
    [/\bIt ran without an error\b/gi, "Elle s'est exécutée sans erreur"],
    [/\band did what it was supposed to do\b/gi, 'et a fait ce qu\'elle devait faire'],
    [/\bIt printed a lot of text\b/gi, "Elle a affiché beaucoup de texte"],
    [/\bThe window closed\b/gi, 'La fenêtre s\'est fermée'],
    [/\bsoftware that does a specific job\b/gi, "logiciel qui fait un travail spécifique"],
    [/\bthe main software\b/gi, 'le logiciel principal'],
    [/\bthat runs the computer\b/gi, "qui fait fonctionner l'ordinateur"],
    [/\bWindows, macOS, and Linux\b/gi, 'Windows, macOS et Linux'],
    [/\bCommand Line Interface\b/gi, 'Interface en Ligne de Commande'],
    [/\bComputer List Input\b/gi, 'Entrée de liste informatique'],
    [/\bCentral Line Index\b/gi, 'Index de ligne central'],
    [/\bClick List Item\b/gi, 'Élément de liste cliquable'],
    [/\bA graphical interface\b/gi, 'Une interface graphique'],
    [/\bwith windows, icons, and mouse clicks\b/gi, 'avec fenêtres, icônes et clics de souris'],
    [/\bA type of\b/gi, 'Un type de'],
    [/\bA kind of\b/gi, 'Une sorte de'],
    [/\bThe blinking line or block\b/gi, 'La ligne ou le bloc clignotant'],
    [/\bwhere your typing appears\b/gi, "où votre saisie s'affiche"],
    [/\bThe mouse pointer\b/gi, 'Le pointeur de la souris'],
    [/\bThe first line of text\b/gi, 'La première ligne de texte'],
    [/\bA command to run\b/gi, 'Une commande à exécuter'],
    [/\bAn error message\b/gi, 'Un message d\'erreur'],
    [/\bThe title of the window\b/gi, 'Le titre de la fenêtre'],
    [/\bA window where you type text commands\b/gi, "Une fenêtre où vous tapez des commandes texte"],
    [/\bfor the computer\b/gi, "pour l'ordinateur"],
    [/\bA type of computer\b/gi, 'Un type d\'ordinateur'],
    [/\bA programming language\b/gi, 'Un langage de programmation'],
    [/\bA kind of cable\b/gi, 'Une sorte de câble'],
    [/\bA click\b/gi, 'Un clic'],
    [/\bA file\b/gi, 'Un fichier'],
    [/\bA window\b/gi, 'Une fenêtre'],
    [/\bEnter \(or Return\)\b/gi, 'Entrée (ou Retour)'],
    [/\bSpace\b(?!\w)/g, 'Espace'],
    [/\bEscape\b/gi, 'Échap'],
    [/\bTab\b(?!\w)/g, 'Tab'],
    [/\bA folder that can hold files and other folders\b/gi, 'Un dossier qui peut contenir des fichiers et d\'autres dossiers'],
    [/\bA type of file\b/gi, 'Un type de fichier'],
    [/\bA command\b/gi, 'Une commande'],
    [/\bA key on the keyboard\b/gi, 'Une touche du clavier'],
    [/\bThe text that appears before the place where you type\b/gi, "Le texte qui s'affiche avant l'endroit où vous tapez"],
    [/\bA command to run\b/gi, 'Une commande à exécuter'],
    [/\bAn error message\b/gi, 'Un message d\'erreur'],
    [/\bThe blinking line or block where your typing appears\b/gi, "La ligne ou le bloc clignotant où votre saisie s'affiche"],
    [/\bThe folder you are in right now\b/gi, 'Le dossier dans lequel vous êtes actuellement'],
    [/\bThe first folder on the computer\b/gi, 'Le premier dossier sur l\'ordinateur'],
    [/\bA file you just opened\b/gi, 'Un fichier que vous venez d\'ouvrir'],
    [/\bYour personal folder\b/gi, 'Votre dossier personnel'],
    [/\boften for your documents and files\b/gi, 'souvent pour vos documents et fichiers'],
    [/\bThe main folder of the computer\b/gi, 'Le dossier principal de l\'ordinateur'],
    [/\bA temporary folder\b/gi, 'Un dossier temporaire'],
    [/\bTo show the names of files and folders\b/gi, 'Afficher les noms des fichiers et dossiers'],
    [/\bTo delete them\b/gi, 'Les supprimer'],
    [/\bTo copy them\b/gi, 'Les copier'],
    [/\bTo create them\b/gi, 'Les créer'],
    [/\bTo move from one folder to another\b/gi, 'Passer d\'un dossier à un autre'],
    [/\bTo delete folders\b/gi, 'Supprimer des dossiers'],
    [/\bTo rename files\b/gi, 'Renommer des fichiers'],
    [/\bTo create files\b/gi, 'Créer des fichiers'],
    [/\bThe location of a file or folder\b/gi, "L'emplacement d'un fichier ou d'un dossier"],
    [/\bwhich folders it is inside\b/gi, 'dans quels dossiers il se trouve'],
    [/\bTyping commands and text\b/gi, 'Taper des commandes et du texte'],
    [/\bOnly for Enter\b/gi, 'Seulement pour Entrée'],
    [/\bOnly for Escape\b/gi, 'Seulement pour Échap'],
    [/\bNothing\b(?!\w)/g, 'Rien'],
    [/\bA folder can contain files and other folders; a file holds data\b/gi, 'Un dossier peut contenir des fichiers et d\'autres dossiers ; un fichier contient des données'],
    [/\bThey are the same\b/gi, "C'est la même chose"],
    [/\bA file is bigger\b/gi, 'Un fichier est plus grand'],
    [/\bA folder is always empty\b/gi, 'Un dossier est toujours vide'],
    [/\bTo tell the computer to do what the command says\b/gi, "Dire à l'ordinateur de faire ce que la commande indique"],
    [/\bTo type it again\b/gi, 'Le retaper'],
    [/\bTo delete it\b/gi, 'Le supprimer'],
    [/\bTo copy it\b/gi, 'Le copier'],
    [/\bThe text the computer prints after you run a command\b/gi, "Le texte que l'ordinateur affiche après avoir exécuté une commande"],
    [/\bThe command you type\b/gi, 'La commande que vous tapez'],
    [/\bAn error\b/gi, 'Une erreur'],
    [/\bThe prompt\b/gi, "L'invite de commande"],
    [/\bWhat you type\b/gi, 'Ce que vous tapez'],
    [/\byour commands and key presses\b/gi, 'vos commandes et touches'],
    [/\bWhat the computer prints\b/gi, "Ce que l'ordinateur affiche"],
    [/\bA file\b/gi, 'Un fichier'],
    [/\bSoftware that does a specific job\b/gi, "Un logiciel qui fait un travail spécifique"],
    [/\b\(e\.g\. list files, edit text\)\b/gi, '(ex. lister les fichiers, éditer le texte)'],
    [/\bA file only\b/gi, 'Un simple fichier'],
    [/\bA folder\b/gi, 'Un dossier'],
    [/\bThe terminal\b/gi, 'Le terminal'],
    [/\bThe main software that runs the computer\b/gi, "Le logiciel principal qui fait fonctionner l'ordinateur"],
    [/\bA single program\b/gi, 'Un seul programme'],
    [/\bA type of file\b/gi, 'Un type de fichier'],
    [/\bThe terminal app\b/gi, "L'application terminal"],
    [/\byou type commands instead of clicking\b/gi, 'vous tapez des commandes au lieu de cliquer'],
    [/\bA graphical interface with windows, icons, and mouse clicks\b/gi, 'Une interface graphique avec fenêtres, icônes et clics souris'],
    [/\bA type of command\b/gi, 'Un type de commande'],
    [/\bA kind of file\b/gi, 'Une sorte de fichier'],
    [/\bEverything must be capitals\b/gi, 'Tout doit être en majuscules'],
    [/\bSpaces do not matter\b/gi, 'Les espaces ne comptent pas'],
    [/\bOnly numbers are allowed\b/gi, 'Seuls les chiffres sont autorisés'],
    [/\bA typing mistake\b/gi, 'Une faute de frappe'],
    [/\bwrong letter or missing character\b/gi, 'mauvaise lettre ou caractère manquant'],
    [/\bA kind of file\b/gi, 'Une sorte de fichier'],
    [/\bA successful result\b/gi, 'Un résultat correct'],
    [/\bIt ran without an error and did what it was supposed to do\b/gi, "Elle s'est exécutée sans erreur et a fait ce qu'elle devait faire"],
    [/\bYou need to press Enter\b/gi, 'Vous devez appuyer sur Entrée'],
    [/\bThe computer does not recognize the word you typed as a command\b/gi, "L'ordinateur ne reconnaît pas le mot que vous avez tapé comme une commande"],
    [/\bThe command worked\b/gi, 'La commande a réussi'],
    [/\bThe file was deleted\b/gi, 'Le fichier a été supprimé'],
    // Level 1+ CLI: commands and concepts
    [/\bthe `pwd` command\b/gi, 'la commande `pwd`'],
    [/\bthe `ls` command\b/gi, 'la commande `ls`'],
    [/\bthe conventional exit code for success\b/gi, "le code de sortie conventionnel pour le succès"],
    [/\b command do\?/gi, ' commande ?'],
    [/\b command display\?/gi, ' commande affiche ?'],
    [/\b add to the output\?/gi, ' ajoute à la sortie ?'],
    [/\b show that normal \S+ hides\?/gi, ' affiche que la commande normale cache ?'],
    [/\bwith no arguments\b/gi, 'sans argument'],
    [/\bthe \* wildcard\b/gi, 'le joker *'],
    [/\bin globbing\b/gi, 'dans le globbing'],
    [/\bFilesystem Hierarchy Standard\b/gi, 'Standard de hiérarchie des systèmes de fichiers (FHS)'],
    [/\buser home directories\b/gi, 'les répertoires personnels des utilisateurs'],
    [/\ban absolute path\b/gi, 'un chemin absolu'],
    [/\ban inode\b/gi, 'un inœud'],
    [/\bFile metadata \(not the filename\)\b/gi, 'Métadonnées du fichier (pas le nom du fichier)'],
    [/\bFile contents\b/gi, 'Contenu du fichier'],
    [/\bDirectory structure\b/gi, 'Structure des répertoires'],
    [/\bFile extension\b/gi, 'Extension du fichier'],
    [/\bhard link\b/gi, 'lien physique'],
    [/\bsymbolic link\b/gi, 'lien symbolique'],
    [/\bfile descriptors 0, 1, and 2\b/gi, 'les descripteurs de fichier 0, 1 et 2'],
    [/\bstdin, stdout, stderr\b/gi, 'stdin, stdout, stderr'],
    [/\bin file permissions\b/gi, 'dans les permissions de fichier'],
    [/\b'r' mean in file permissions\b/gi, "'r' signifie dans les permissions de fichier"],
    [/\bOnly root\b/gi, 'Seul root'],
    [/\bFile owner\b/gi, 'Propriétaire du fichier'],
    [/\bAnyone in group\b/gi, 'Tout le monde dans le groupe'],
    [/\bAnyone\b(?!\w)/g, 'Tout le monde'],
    [/\bAttaches a filesystem to a directory\b/gi, 'Attache un système de fichiers à un répertoire'],
    [/\bOutputs file contents to stdout\b/gi, 'Envoie le contenu du fichier sur la sortie standard'],
    [/\bScroll backward and forward\b/gi, 'Défiler en arrière et en avant'],
    [/\bFirst 5 lines\b/gi, 'Les 5 premières lignes'],
    [/\bLine count\b/gi, 'Nombre de lignes'],
    [/\bSort lines alphabetically\b/gi, 'Trier les lignes par ordre alphabétique'],
    [/\bSorted input \(adjacent duplicates\)\b/gi, 'Entrée triée (doublons adjacents)'],
    [/\bLong format with permissions and details\b/gi, 'Format long avec permissions et détails'],
    [/\bYour home directory path\b/gi, 'Le chemin de votre répertoire personnel'],
    [/\bHidden files \(dotfiles\)\b/gi, 'Fichiers cachés (fichiers point)'],
    [/\bGo to home directory\b/gi, 'Aller au répertoire personnel'],
    [/\bGo up one directory\b/gi, 'Remonter d\'un répertoire'],
    [/\bPrint working directory\b/gi, 'Afficher le répertoire de travail'],
    [/\bDirectory contents\b/gi, 'Contenu du répertoire'],
    [/\bCreates a directory named mydir\b/gi, 'Crée un répertoire nommé mydir'],
    [/\bAny string of characters\b/gi, 'N\'importe quelle chaîne de caractères'],
    [/\bA single character\b/gi, 'Un seul caractère'],
    [/\bDeletes file\.txt\b/gi, 'Supprime file.txt'],
    [/\bRuns with owner's privileges\b/gi, "S'exécute avec les privilèges du propriétaire"],
    [/\bFirst column \(comma-delimited\)\b/gi, 'Première colonne (séparée par des virgules)'],
    [/\bMerges lines side-by-side\b/gi, 'Fusionne les lignes côte à côte'],
    [/\bTranslates lowercase to uppercase\b/gi, 'Traduit les minuscules en majuscules'],
    [/\bWrites stdin to file and stdout\b/gi, 'Écrit l\'entrée standard dans un fichier et sur la sortie standard'],
    // Level 4: Process management
    [/\bSnapshot of running processes\b/gi, 'Instantané des processus en cours'],
    [/\bInteractive real-time process monitor\b/gi, 'Moniteur de processus interactif en temps réel'],
    [/\bSIGTERM \(15\)\b/gi, 'SIGTERM (15)'],
    [/\bSIGKILL \(9\)\b/gi, 'SIGKILL (9)'],
    [/\bForce-kills process \(SIGKILL\)\b/gi, 'Tue le processus de force (SIGKILL)'],
    [/\bProcess scheduling priority \(nice value\)\b/gi, 'Priorité d\'ordonnancement du processus (valeur nice)'],
    [/\bSchedules jobs at specified times\b/gi, 'Planifie des tâches à des heures définies'],
    [/\bBackground process that runs without a terminal\b/gi, 'Processus en arrière-plan sans terminal'],
    [/\bStarts a systemd service\b/gi, 'Démarre un service systemd'],
    [/\bUptime and load averages\b/gi, 'Temps de fonctionnement et charge moyenne'],
    [/\bMemory and swap usage \(human-readable\)\b/gi, 'Utilisation mémoire et swap (lisible)'],
    [/\bDisk space used as virtual memory\b/gi, 'Espace disque utilisé comme mémoire virtuelle'],
    [/\bFinds PIDs matching process name\b/gi, 'Trouve les PIDs correspondant au nom du processus'],
    [/\bSends signal to processes matching name\b/gi, 'Envoie un signal aux processus correspondant au nom'],
    [/\bBackground and suspended jobs in current shell\b/gi, 'Tâches en arrière-plan et suspendues dans le shell courant'],
    // Level 5: Package management
    [/\bRefreshes package index from repositories\b/gi, 'Met à jour l\'index des paquets depuis les dépôts'],
    [/\bUpgrades installed packages to latest versions\b/gi, 'Met à jour les paquets installés vers les dernières versions'],
    [/\bInstalls package and dependencies\b/gi, 'Installe le paquet et ses dépendances'],
    [/\bRemoves package but keeps config files\b/gi, 'Supprime le paquet mais garde les fichiers de config'],
    [/\bSearches package names and descriptions\b/gi, 'Recherche dans les noms et descriptions des paquets'],
    [/\bInstalls package \(RHEL\/Fedora\)\b/gi, 'Installe le paquet (RHEL/Fedora)'],
    [/\bInstalls package via Homebrew \(macOS\/Linux\)\b/gi, 'Installe le paquet via Homebrew (macOS/Linux)'],
    [/\bInstalls snap package \(sandboxed\)\b/gi, 'Installe un paquet snap (sandboxé)'],
    [/\bInstalls Flatpak application \(sandboxed\)\b/gi, 'Installe une application Flatpak (sandboxée)'],
    [/\bBuilds project using Makefile\b/gi, 'Compile le projet avec le Makefile'],
    [/\bConfigures build for your system before make\b/gi, 'Configure la compilation pour votre système avant make'],
    [/\bInstalls \.deb file directly \(no dependency resolution\)\b/gi, 'Installe le fichier .deb directement (sans résolution des dépendances)'],
    [/\bList of installed packages\b/gi, 'Liste des paquets installés'],
    // Level 6: Networking
    [/\bSends ICMP echo requests to test connectivity\b/gi, 'Envoie des requêtes ICMP echo pour tester la connectivité'],
    [/\bTransfers data from URL \(HTTP, FTP, etc\.\)\b/gi, 'Transfère des données depuis une URL (HTTP, FTP, etc.)'],
    [/\bDownloads file from URL\b/gi, 'Télécharge un fichier depuis une URL'],
    [/\bConnects to remote host via SSH\b/gi, 'Se connecte à l\'hôte distant via SSH'],
    [/\bCopies file to remote host over SSH\b/gi, 'Copie le fichier vers l\'hôte distant via SSH'],
    [/\bSyncs files \(archive, verbose\)\. Efficient for transfers\b/gi, 'Synchronise les fichiers (archive, verbeux). Efficace pour les transferts'],
    [/\bNumber \(0-65535\) identifying service\/application\b/gi, 'Numéro (0-65535) identifiant le service ou l\'application'],
    [/\bQueries DNS for domain info\b/gi, 'Interroge le DNS pour les infos du domaine'],
    [/\bDNS lookup with detailed output\b/gi, 'Requête DNS avec sortie détaillée'],
    [/\bNetwork interface configuration \(legacy\)\b/gi, 'Configuration des interfaces réseau (ancien)'],
    [/\bIP addresses and interface info\b/gi, 'Adresses IP et infos des interfaces'],
    [/\bListening TCP ports and processes\b/gi, 'Ports TCP en écoute et processus'],
    [/\bSocket statistics \(listening TCP, processes\)\b/gi, 'Statistiques des sockets (TCP en écoute, processus)'],
    // Level 7: Advanced networking
    [/\bAdds IP address to interface\b/gi, 'Ajoute une adresse IP à l\'interface'],
    [/\bBrings interface up\b/gi, 'Met l\'interface en service'],
    [/\bAdds default gateway\b/gi, 'Ajoute la passerelle par défaut'],
    [/\bLists firewall rules\b/gi, 'Liste les règles du pare-feu'],
    [/\bAllows incoming SSH \(port 22\)\b/gi, 'Autorise les connexions SSH entrantes (port 22)'],
    [/\bSets default policy for INPUT to DROP\b/gi, 'Définit la politique par défaut d\'INPUT sur DROP'],
    [/\bAll nftables rules\b/gi, 'Toutes les règles nftables'],
    [/\bCreates bridge interface\b/gi, 'Crée une interface pont'],
    [/\bVirtual LAN \(802\.1Q tagged network\)\b/gi, 'Réseau local virtuel (réseau étiqueté 802.1Q)'],
    [/\bCreates VLAN 10 on eth0\b/gi, 'Crée le VLAN 10 sur eth0'],
    [/\bCaptures packets on port 80\b/gi, 'Capture les paquets sur le port 80'],
    [/\bEstablished TCP connections\b/gi, 'Connexions TCP établies'],
    [/\bConnection tracking table\b/gi, 'Table de suivi des connexions'],
    [/\bNAT table rules\b/gi, 'Règles de la table NAT'],
    // Level 8: Security
    [/\bChanges user password\b/gi, 'Change le mot de passe utilisateur'],
    [/\bCreates new user account\b/gi, 'Crée un nouveau compte utilisateur'],
    [/\bAdds user to supplementary group\b/gi, 'Ajoute l\'utilisateur à un groupe secondaire'],
    [/\bOwner read\+write only \(rw-------\)\b/gi, 'Propriétaire lecture+écriture uniquement (rw-------)'],
    [/\bOwner full access, none for others \(rwx------\)\b/gi, 'Propriétaire accès total, aucun pour les autres (rwx------)'],
    [/\bSafely edits sudoers file\b/gi, 'Modifie le fichier sudoers en toute sécurité'],
    [/\bYour sudo privileges\b/gi, 'Vos privilèges sudo'],
    [/\bSwitches to user with login shell\b/gi, 'Passe à l\'utilisateur avec shell de connexion'],
    [/\bUser and group IDs\b/gi, 'UID et GID utilisateur'],
    [/\bLogged-in users\b/gi, 'Utilisateurs connectés'],
    [/\bLogin history\b/gi, 'Historique des connexions'],
    [/\bFailed login attempts\b/gi, 'Tentatives de connexion échouées'],
    // Level 9: Pentest
    [/\bProbes open ports for service\/version\b/gi, 'Sonde les ports ouverts pour service/version'],
    [/\bRuns default NSE scripts\b/gi, 'Exécute les scripts NSE par défaut'],
    [/\bAttempts OS detection\b/gi, 'Tente la détection de l\'OS'],
    [/\bScans all 65535 ports\b/gi, 'Scanne les 65535 ports'],
    [/\bSYN scan \(half-open, stealthier\)\b/gi, 'Scan SYN (demi-ouvert, plus furtif)'],
    [/\bUDP scan on DNS and SNMP ports\b/gi, 'Scan UDP sur les ports DNS et SNMP'],
    [/\bRuns vulnerability detection scripts\b/gi, 'Exécute les scripts de détection de vulnérabilités'],
    [/\bWeb server vulnerability scanner\b/gi, 'Scanner de vulnérabilités serveur web'],
    [/\bDirectory\/file brute force\b/gi, 'Brute force répertoires/fichiers'],
    [/\bSubdomain enumeration\b/gi, 'Énumération des sous-domaines'],
    [/\bSearches Exploit-DB for exploits\b/gi, 'Recherche des exploits dans Exploit-DB'],
    [/\bMetasploit Framework console\b/gi, 'Console Metasploit Framework'],
    // Level 10: Docker, Git
    [/\bRuns nginx container\b/gi, 'Lance le conteneur nginx'],
    [/\bRunning containers\b/gi, 'Conteneurs en cours d\'exécution'],
    [/\bBuilds image from Dockerfile in current dir\b/gi, 'Construit l\'image depuis le Dockerfile du répertoire courant'],
    [/\bRuns bash in running container\b/gi, 'Lance bash dans le conteneur en cours'],
    [/\bStops container \(SIGTERM then SIGKILL\)\b/gi, 'Arrête le conteneur (SIGTERM puis SIGKILL)'],
    [/\bRemoves stopped container\b/gi, 'Supprime le conteneur arrêté'],
    [/\bList of images\b/gi, 'Liste des images'],
    [/\bDownloads image from registry\b/gi, 'Télécharge l\'image depuis le registre'],
    [/\bMaps host 8080 to container 80\b/gi, 'Mappe l\'hôte 8080 vers le conteneur 80'],
    [/\bMounts host directory into container\b/gi, 'Monte le répertoire hôte dans le conteneur'],
    [/\bCreates new Git repository\b/gi, 'Crée un nouveau dépôt Git'],
    [/\bClones remote repository\b/gi, 'Clone le dépôt distant'],
  ];

  for (const [pattern, replacement] of phraseTranslations) {
    translated = translated.replace(pattern, replacement);
  }

  return sanitizeFrenchArtifacts(translated);
};

/**
 * Translates option text (A/B/C/D choices) to French when language is 'fr'.
 * Used so the entire quiz panel is in French in French mode.
 */
export const translateOptionText = (text: string, language: string): string => {
  if (language !== 'fr') return text;

  // Logical fallacy quiz options: use French fallacy names so every question's A/B/C/D are in French
  const fallacyFr = getFallacyOptionFrench(text);
  if (fallacyFr !== text) return fallacyFr;

  const optionTranslations: Array<[RegExp, string]> = [
    [/\bA window where you type text commands for the computer\b/gi, "Une fenêtre où vous tapez des commandes texte pour l'ordinateur"],
    [/\bA type of computer\b/gi, "Un type d'ordinateur"],
    [/\bA programming language\b/gi, 'Un langage de programmation'],
    [/\bA kind of cable\b/gi, 'Une sorte de câble'],
    [/\bA command\b/gi, 'Une commande'],
    [/\bA click\b/gi, 'Un clic'],
    [/\bA file\b/gi, 'Un fichier'],
    [/\bA window\b/gi, 'Une fenêtre'],
    [/\bEnter \(or Return\)\b/gi, 'Entrée (ou Retour)'],
    [/\bSpace\b(?!\w)/g, 'Espace'],
    [/\bEscape\b/gi, 'Échap'],
    [/\bTab\b(?!\w)/g, 'Tab'],
    [/\bA folder that can hold files and other folders\b/gi, 'Un dossier qui peut contenir des fichiers et d\'autres dossiers'],
    [/\bA type of file\b/gi, 'Un type de fichier'],
    [/\bThe blinking line in the terminal\b/gi, 'La ligne clignotante dans le terminal'],
    [/\bA key\b/gi, 'Une touche'],
    [/\bThe text that appears before the place where you type\b/gi, "Le texte qui s'affiche avant l'endroit où vous tapez"],
    [/\bA command to run\b/gi, 'Une commande à exécuter'],
    [/\bAn error message\b/gi, 'Un message d\'erreur'],
    [/\bThe title of the window\b/gi, 'Le titre de la fenêtre'],
    [/\bThe blinking line or block where your typing appears\b/gi, "La ligne ou le bloc clignotant où votre saisie s'affiche"],
    [/\bThe mouse pointer\b/gi, 'Le pointeur de la souris'],
    [/\bThe first line of text\b/gi, 'La première ligne de texte'],
    [/\bNo\b(?!\w)/g, 'Non'],
    [/\bYes\b(?!\w)/g, 'Oui'],
    [/\bOnly on Windows\b/gi, 'Seulement sur Windows'],
    [/\bOnly on Mac\b/gi, 'Seulement sur Mac'],
    [/\bThe command line \(or terminal\)\b/gi, 'La ligne de commande (ou terminal)'],
    [/\bThe desktop\b/gi, 'Le bureau'],
    [/\bThe menu bar\b/gi, 'La barre de menus'],
    [/\bThe taskbar\b/gi, 'La barre des tâches'],
    [/\bThe folder you are in right now\b/gi, 'Le dossier dans lequel vous êtes actuellement'],
    [/\bThe first folder on the computer\b/gi, 'Le premier dossier sur l\'ordinateur'],
    [/\bA file you just opened\b/gi, 'Un fichier que vous venez d\'ouvrir'],
    [/\bYour personal folder \(often for your documents and files\)\b/gi, 'Votre dossier personnel (souvent pour vos documents et fichiers)'],
    [/\bThe main folder of the computer\b/gi, 'Le dossier principal de l\'ordinateur'],
    [/\bA temporary folder\b/gi, 'Un dossier temporaire'],
    [/\bTo show the names of files and folders\b/gi, 'Afficher les noms des fichiers et dossiers'],
    [/\bTo delete them\b/gi, 'Les supprimer'],
    [/\bTo copy them\b/gi, 'Les copier'],
    [/\bTo create them\b/gi, 'Les créer'],
    [/\bTo move from one folder to another\b/gi, 'Passer d\'un dossier à un autre'],
    [/\bTo delete folders\b/gi, 'Supprimer des dossiers'],
    [/\bTo rename files\b/gi, 'Renommer des fichiers'],
    [/\bTo create files\b/gi, 'Créer des fichiers'],
    [/\bThe location of a file or folder \(e\.g\. which folders it is inside\)\b/gi, "L'emplacement d'un fichier ou dossier (ex. dans quels dossiers il se trouve)"],
    [/\bA command\b/gi, 'Une commande'],
    [/\bA type of file\b/gi, 'Un type de fichier'],
    [/\bThe prompt\b/gi, "L'invite de commande"],
    [/\bTyping commands and text\b/gi, 'Taper des commandes et du texte'],
    [/\bOnly for Enter\b/gi, 'Seulement pour Entrée'],
    [/\bOnly for Escape\b/gi, 'Seulement pour Échap'],
    [/\bNothing\b(?!\w)/g, 'Rien'],
    [/\bA folder can contain files and other folders; a file holds data\b/gi, 'Un dossier peut contenir des fichiers et d\'autres dossiers ; un fichier contient des données'],
    [/\bThey are the same\b/gi, "C'est la même chose"],
    [/\bA file is bigger\b/gi, 'Un fichier est plus grand'],
    [/\bA folder is always empty\b/gi, 'Un dossier est toujours vide'],
    [/\bTo tell the computer to do what the command says\b/gi, "Dire à l'ordinateur de faire ce que la commande indique"],
    [/\bTo type it again\b/gi, 'Le retaper'],
    [/\bTo delete it\b/gi, 'Le supprimer'],
    [/\bTo copy it\b/gi, 'Le copier'],
    [/\bThe text the computer prints after you run a command\b/gi, "Le texte que l'ordinateur affiche après avoir exécuté une commande"],
    [/\bThe command you type\b/gi, 'La commande que vous tapez'],
    [/\bAn error\b/gi, 'Une erreur'],
    [/\bWhat you type \(your commands and key presses\)\b/gi, 'Ce que vous tapez (vos commandes et touches)'],
    [/\bWhat the computer prints\b/gi, "Ce que l'ordinateur affiche"],
    [/\bA file\b/gi, 'Un fichier'],
    [/\bSoftware that does a specific job \(e\.g\. list files, edit text\)\b/gi, 'Un logiciel qui fait un travail spécifique (ex. lister les fichiers, éditer le texte)'],
    [/\bA file only\b/gi, 'Un simple fichier'],
    [/\bA folder\b/gi, 'Un dossier'],
    [/\bThe terminal\b/gi, 'Le terminal'],
    [/\bThe main software that runs the computer \(e\.g\. Windows, macOS, Linux\)\b/gi, "Le logiciel principal qui fait fonctionner l'ordinateur (ex. Windows, macOS, Linux)"],
    [/\bA single program\b/gi, 'Un seul programme'],
    [/\bThe terminal app\b/gi, "L'application terminal"],
    [/\bCommand Line Interface\b/gi, 'Interface en Ligne de Commande'],
    [/\bComputer List Input\b/gi, 'Entrée de liste informatique'],
    [/\bCentral Line Index\b/gi, 'Index de ligne central'],
    [/\bClick List Item\b/gi, 'Élément de liste cliquable'],
    [/\bA graphical interface with windows, icons, and mouse clicks\b/gi, 'Une interface graphique avec fenêtres, icônes et clics souris'],
    [/\bA type of command\b/gi, 'Un type de commande'],
    [/\bA kind of file\b/gi, 'Une sorte de fichier'],
    [/\bCapital and small letters are different \(e\.g\. A vs a\)\b/gi, 'Les majuscules et les minuscules sont différentes (ex. A et a)'],
    [/\bEverything must be capitals\b/gi, 'Tout doit être en majuscules'],
    [/\bSpaces do not matter\b/gi, 'Les espaces ne comptent pas'],
    [/\bOnly numbers are allowed\b/gi, 'Seuls les chiffres sont autorisés'],
    [/\bA typing mistake \(e\.g\. wrong letter or missing character\)\b/gi, 'Une faute de frappe (ex. mauvaise lettre ou caractère manquant)'],
    [/\bA kind of file\b/gi, 'Une sorte de fichier'],
    [/\bText from the computer saying something went wrong\b/gi, "Texte de l'ordinateur indiquant qu'une erreur s'est produite"],
    [/\bA successful result\b/gi, 'Un résultat correct'],
    [/\bThe prompt\b/gi, "L'invite de commande"],
    [/\bIt ran without an error and did what it was supposed to do\b/gi, "Elle s'est exécutée sans erreur et a fait ce qu'elle devait faire"],
    [/\bIt printed a lot of text\b/gi, "Elle a affiché beaucoup de texte"],
    [/\bYou pressed Enter\b/gi, 'Vous avez appuyé sur Entrée'],
    [/\bThe window closed\b/gi, 'La fenêtre s\'est fermée'],
    [/\bThe computer does not recognize the word you typed as a command\b/gi, "L'ordinateur ne reconnaît pas le mot que vous avez tapé comme une commande"],
    [/\bThe command worked\b/gi, 'La commande a réussi'],
    [/\bThe file was deleted\b/gi, 'Le fichier a été supprimé'],
    [/\bYou need to press Enter\b/gi, 'Vous devez appuyer sur Entrée'],
    // Generic phrase replacements for options (order matters: longer first)
    [/\bthe computer\b/gi, "l'ordinateur"],
    [/\bthe terminal\b/gi, 'le terminal'],
    [/\ba terminal\b/gi, 'un terminal'],
    [/\ba command\b/gi, 'une commande'],
    [/\bthe command\b/gi, 'la commande'],
    [/\ba directory\b/gi, 'un répertoire'],
    [/\bthe directory\b/gi, 'le répertoire'],
    [/\ba file\b/gi, 'un fichier'],
    [/\bthe file\b/gi, 'le fichier'],
    [/\bthe prompt\b/gi, 'l\'invite de commande'],
    [/\ba folder\b/gi, 'un dossier'],
    [/\bthe folder\b/gi, 'le dossier'],
    [/\bthe keyboard\b/gi, 'le clavier'],
    [/\bthe cursor\b/gi, 'le curseur'],
    [/\bthe window\b/gi, 'la fenêtre'],
    [/\bthe screen\b/gi, "l'écran"],
    [/\bthe line\b/gi, 'la ligne'],
    [/\bthe text\b/gi, 'le texte'],
    [/\bthe name\b/gi, 'le nom'],
    [/\bthe output\b/gi, 'la sortie'],
    [/\bthe input\b/gi, "l'entrée"],
    [/\bfor the computer\b/gi, "pour l'ordinateur"],
    [/\byou type\b/gi, 'vous tapez'],
    [/\bwhere you type\b/gi, 'où vous tapez'],
    [/\bthat appears\b/gi, 'qui s\'affiche'],
    [/\bthat shows\b/gi, 'qui affiche'],
    [/\bto run\b/gi, 'exécuter'],
    [/\bto execute\b/gi, 'exécuter'],
    [/\bto show\b/gi, 'afficher'],
    [/\bto create\b/gi, 'créer'],
    [/\bto delete\b/gi, 'supprimer'],
    [/\bto copy\b/gi, 'copier'],
    [/\bto move\b/gi, 'déplacer'],
    [/\bto list\b/gi, 'lister'],
    [/\bto navigate\b/gi, 'naviguer'],
    [/\bwithout an error\b/gi, 'sans erreur'],
    [/\bwith a name\b/gi, 'avec un nom'],
    // Level 1–3 CLI options (longer phrases first)
    [/\bPrint working directory\b/gi, 'Afficher le répertoire de travail'],
    [/\bPrint file contents\b/gi, 'Afficher le contenu du fichier'],
    [/\bChange directory\b/gi, 'Changer de répertoire'],
    [/\bList files\b/gi, 'Lister les fichiers'],
    [/\bDirectory contents\b/gi, 'Contenu du répertoire'],
    [/\bFile contents\b/gi, 'Contenu du fichier'],
    [/\bCurrent path\b/gi, 'Chemin courant'],
    [/\bEnvironment variables\b/gi, 'Variables d\'environnement'],
    [/\bGo up one directory\b/gi, 'Remonter d\'un répertoire'],
    [/\bGo to home\b/gi, 'Aller au répertoire personnel'],
    [/\bCreate a directory\b/gi, 'Créer un répertoire'],
    [/\bDelete current directory\b/gi, 'Supprimer le répertoire courant'],
    [/\bCreates a directory named mydir\b/gi, 'Crée un répertoire nommé mydir'],
    [/\bRemoves mydir\b/gi, 'Supprime mydir'],
    [/\bMoves into mydir\b/gi, 'Entre dans mydir'],
    [/\bLists mydir\b/gi, 'Liste mydir'],
    [/\bAny string of characters\b/gi, 'N\'importe quelle chaîne de caractères'],
    [/\bA single character\b/gi, 'Un seul caractère'],
    [/\bOnly digits\b/gi, 'Seuls les chiffres'],
    [/\bOnly letters\b/gi, 'Seules les lettres'],
    [/\bLong format with permissions and details\b/gi, 'Format long avec permissions et détails'],
    [/\bOnly hidden files\b/gi, 'Seuls les fichiers cachés'],
    [/\bRecursive listing\b/gi, 'Listage récursif'],
    [/\bReverse order\b/gi, 'Ordre inverse'],
    [/\bYour home directory path\b/gi, 'Le chemin de votre répertoire personnel'],
    [/\bCurrent directory\b/gi, 'Répertoire courant'],
    [/\bThe word HOME\b/gi, 'Le mot HOME'],
    [/\bEnvironment count\b/gi, 'Nombre de variables d\'environnement'],
    [/\bHidden files \(dotfiles\)\b/gi, 'Fichiers cachés (fichiers point)'],
    [/\bLarge files only\b/gi, 'Seuls les gros fichiers'],
    [/\bExecutable files only\b/gi, 'Seuls les fichiers exécutables'],
    [/\bRecent files only\b/gi, 'Seuls les fichiers récents'],
    [/\bGo to home directory\b/gi, 'Aller au répertoire personnel'],
    [/\bStay in current directory\b/gi, 'Rester dans le répertoire courant'],
    [/\bShow current path\b/gi, 'Afficher le chemin courant'],
    [/\bList directories\b/gi, 'Lister les répertoires'],
    [/\bDeletes file\.txt\b/gi, 'Supprime file.txt'],
    [/\bRenames file\.txt\b/gi, 'Renomme file.txt'],
    [/\bMoves file\.txt\b/gi, 'Déplace file.txt'],
    [/\bCopies file\.txt\b/gi, 'Copie file.txt'],
    [/\b\/home\b/g, '/home'],
    [/\b\/usr\/home\b/g, '/usr/home'],
    [/\b\/var\/home\b/g, '/var/home'],
    [/\b\/opt\/home\b/g, '/opt/home'],
    [/\bFile metadata \(not the filename\)\b/gi, 'Métadonnées du fichier (pas le nom)'],
    [/\bDirectory structure\b/gi, 'Structure des répertoires'],
    [/\bFile extension\b/gi, 'Extension du fichier'],
    [/\bHard link\b/gi, 'Lien physique'],
    [/\bSymbolic link\b/gi, 'Lien symbolique'],
    [/\bCopy\b(?!\w)/g, 'Copie'],
    [/\bShortcut\b/gi, 'Raccourci'],
    [/\bstdin, stdout, stderr\b/gi, 'stdin, stdout, stderr'],
    [/\bread, write, execute\b/gi, 'lecture, écriture, exécution'],
    [/\binput, output, error\b/gi, 'entrée, sortie, erreur'],
    [/\bRead\b(?!\w)/g, 'Lecture'],
    [/\bRun\b(?!\w)/g, 'Exécution'],
    [/\bRemove\b(?!\w)/g, 'Suppression'],
    [/\bRecursive\b(?!\w)/g, 'Récursif'],
    [/\bOnly root\b/gi, 'Seul root'],
    [/\bFile owner\b/gi, 'Propriétaire du fichier'],
    [/\bRuns with owner's privileges\b/gi, "S'exécute avec les privilèges du propriétaire"],
    [/\bRuns as root always\b/gi, 'S\'exécute toujours en root'],
    [/\bMakes it system-only\b/gi, 'Réservé au système'],
    [/\bDisables execution\b/gi, 'Désactive l\'exécution'],
    [/\bAttaches a filesystem to a directory\b/gi, 'Attache un système de fichiers à un répertoire'],
    [/\bCreates a partition\b/gi, 'Crée une partition'],
    [/\bFormats a disk\b/gi, 'Formate un disque'],
    [/\bLists disks\b/gi, 'Liste les disques'],
    [/\bOutputs file contents to stdout\b/gi, 'Envoie le contenu du fichier sur la sortie standard'],
    [/\bCreates file\b/gi, 'Crée un fichier'],
    [/\bCopies file\b/gi, 'Copie le fichier'],
    [/\bCatalogs file\b/gi, 'Cataloguer le fichier'],
    [/\bScroll backward and forward\b/gi, 'Défiler en arrière et en avant'],
    [/\bOnly forward scroll\b/gi, 'Défilement avant uniquement'],
    [/\bNo difference\b/gi, 'Aucune différence'],
    [/\bFaster output\b/gi, 'Sortie plus rapide'],
    [/\bFirst 5 lines\b/gi, 'Les 5 premières lignes'],
    [/\bFirst 5 bytes\b/gi, 'Les 5 premiers octets'],
    [/\bLines 1-5 only\b/gi, 'Lignes 1 à 5 uniquement'],
    [/\bTop 5 words\b/gi, 'Les 5 premiers mots'],
    [/\bLast 5 lines\b/gi, 'Les 5 dernières lignes'],
    [/\bLast 5 bytes\b/gi, 'Les 5 derniers octets'],
    [/\bBottom 5\b/gi, 'Les 5 derniers'],
    [/\bLines from 5\b/gi, 'Lignes à partir de 5'],
    [/\bLine count\b/gi, 'Nombre de lignes'],
    [/\bWord count\b/gi, 'Nombre de mots'],
    [/\bCharacter count\b/gi, 'Nombre de caractères'],
    [/\bByte count\b/gi, 'Nombre d\'octets'],
    [/\bSort lines alphabetically\b/gi, 'Trier les lignes par ordre alphabétique'],
    [/\bSort numerically\b/gi, 'Trier numériquement'],
    [/\bReverse sort\b/gi, 'Tri inverse'],
    [/\bRandom sort\b/gi, 'Tri aléatoire'],
    [/\bSorted input \(adjacent duplicates\)\b/gi, 'Entrée triée (doublons adjacents)'],
    [/\bUnique file\b/gi, 'Fichier unique'],
    [/\bSingle column\b/gi, 'Une seule colonne'],
    [/\bSmall file\b/gi, 'Petit fichier'],
    [/\bFirst column \(comma-delimited\)\b/gi, 'Première colonne (séparée par des virgules)'],
    [/\bDeletes first column\b/gi, 'Supprime la première colonne'],
    [/\bCuts at comma\b/gi, 'Découpe à la virgule'],
    [/\bField 1 only\b/gi, 'Champ 1 uniquement'],
    [/\bMerges lines side-by-side\b/gi, 'Fusionne les lignes côte à côte'],
    [/\bConcatenates vertically\b/gi, 'Concatène verticalement'],
    [/\bCompares files\b/gi, 'Compare les fichiers'],
    [/\bPastes clipboard\b/gi, 'Colle le presse-papiers'],
    [/\bTranslates lowercase to uppercase\b/gi, 'Traduit les minuscules en majuscules'],
    [/\bTransposes chars\b/gi, 'Transpose les caractères'],
    [/\bReplaces a-z\b/gi, 'Remplace a-z'],
    [/\bTrims spaces\b/gi, 'Supprime les espaces'],
    [/\bWrites stdin to file and stdout\b/gi, 'Écrit l\'entrée standard dans un fichier et sur la sortie standard'],
    [/\bCreates pipe\b/gi, 'Crée un tube'],
    [/\bAppends to file\b/gi, 'Ajoute au fichier'],
    [/\bReads file\b/gi, 'Lit le fichier'],
    // Level 4: Process
    [/\bSnapshot of running processes\b/gi, 'Instantané des processus en cours'],
    [/\bProcess status only\b/gi, 'Statut des processus uniquement'],
    [/\bCPU usage\b/gi, 'Utilisation CPU'],
    [/\bMemory usage\b/gi, 'Utilisation mémoire'],
    [/\bInteractive real-time process monitor\b/gi, 'Moniteur de processus interactif en temps réel'],
    [/\bLists top processes only\b/gi, 'Liste uniquement les principaux processus'],
    [/\bProcess tree\b/gi, 'Arbre des processus'],
    [/\bCPU top 10\b/gi, 'Top 10 CPU'],
    [/\bSIGTERM \(15\)\b/gi, 'SIGTERM (15)'],
    [/\bSIGKILL \(9\)\b/gi, 'SIGKILL (9)'],
    [/\bSIGINT \(2\)\b/gi, 'SIGINT (2)'],
    [/\bSIGSTOP \(19\)\b/gi, 'SIGSTOP (19)'],
    [/\bForce-kills process \(SIGKILL\)\b/gi, 'Tue le processus de force (SIGKILL)'],
    [/\bSends signal 9 only\b/gi, 'Envoie uniquement le signal 9'],
    [/\bPauses process\b/gi, 'Met le processus en pause'],
    [/\bSends SIGTERM\b/gi, 'Envoie SIGTERM'],
    [/\bProcess scheduling priority \(nice value\)\b/gi, 'Priorité d\'ordonnancement (valeur nice)'],
    [/\bProcess name\b/gi, 'Nom du processus'],
    [/\bCPU affinity\b/gi, 'Affinité CPU'],
    [/\bMemory limit\b/gi, 'Limite mémoire'],
    [/\bSchedules jobs at specified times\b/gi, 'Planifie des tâches à des heures définies'],
    [/\bRuns jobs once\b/gi, 'Exécute les tâches une fois'],
    [/\bManages cron daemon\b/gi, 'Gère le démon cron'],
    [/\bLists cron jobs\b/gi, 'Liste les tâches cron'],
    [/\bBackground process that runs without a terminal\b/gi, 'Processus en arrière-plan sans terminal'],
    [/\bA system service\b/gi, 'Un service système'],
    [/\bA cron job\b/gi, 'Une tâche cron'],
    [/\bAn init process\b/gi, 'Un processus init'],
    [/\bStarts a systemd service\b/gi, 'Démarre un service systemd'],
    [/\bStarts a process\b/gi, 'Démarre un processus'],
    [/\bStarts cron\b/gi, 'Démarre cron'],
    [/\bStarts init\b/gi, 'Démarre init'],
    [/\bUptime and load averages\b/gi, 'Temps de fonctionnement et charge moyenne'],
    [/\bProcess count\b/gi, 'Nombre de processus'],
    [/\bMemory and swap usage \(human-readable\)\b/gi, 'Utilisation mémoire et swap (lisible)'],
    [/\bFree disk space\b/gi, 'Espace disque libre'],
    [/\bFree processes\b/gi, 'Processus libres'],
    [/\bFree CPU\b/gi, 'CPU libre'],
    [/\bDisk space used as virtual memory\b/gi, 'Espace disque utilisé comme mémoire virtuelle'],
    [/\bMemory swap\b/gi, 'Échange mémoire'],
    [/\bProcess swap\b/gi, 'Échange de processus'],
    [/\bCPU swap\b/gi, 'Échange CPU'],
    [/\bFinds PIDs matching process name\b/gi, 'Trouve les PIDs correspondant au nom du processus'],
    [/\bPrints process list\b/gi, 'Affiche la liste des processus'],
    [/\bProcess grep\b/gi, 'Grep de processus'],
    [/\bProcess group\b/gi, 'Groupe de processus'],
    [/\bSends signal to processes matching name\b/gi, 'Envoie un signal aux processus correspondant au nom'],
    [/\bPrints matching processes\b/gi, 'Affiche les processus correspondants'],
    [/\bKills by PID\b/gi, 'Tue par PID'],
    [/\bProcess kill list\b/gi, 'Liste de processus à tuer'],
    [/\bBackground and suspended jobs in current shell\b/gi, 'Tâches en arrière-plan et suspendues dans le shell courant'],
    [/\bAll system jobs\b/gi, 'Toutes les tâches système'],
    [/\bCron jobs\b/gi, 'Tâches cron'],
    [/\bSystemd jobs\b/gi, 'Tâches systemd'],
    // Level 5: Packages
    [/\bRefreshes package index from repositories\b/gi, 'Met à jour l\'index des paquets depuis les dépôts'],
    [/\bUpdates all packages\b/gi, 'Met à jour tous les paquets'],
    [/\bUpdates apt itself\b/gi, 'Met à jour apt lui-même'],
    [/\bUpdates kernel\b/gi, 'Met à jour le noyau'],
    [/\bUpgrades installed packages to latest versions\b/gi, 'Met à jour les paquets installés vers les dernières versions'],
    [/\bUpdates repository list\b/gi, 'Met à jour la liste des dépôts'],
    [/\bUpgrades system\b/gi, 'Met à jour le système'],
    [/\bUpgrades kernel only\b/gi, 'Met à jour uniquement le noyau'],
    [/\bInstalls package and dependencies\b/gi, 'Installe le paquet et ses dépendances'],
    [/\bInstalls package only\b/gi, 'Installe uniquement le paquet'],
    [/\bDownloads package\b/gi, 'Télécharge le paquet'],
    [/\bConfigures package\b/gi, 'Configure le paquet'],
    [/\bRemoves package but keeps config files\b/gi, 'Supprime le paquet mais garde les fichiers de config'],
    [/\bRemoves package and config\b/gi, 'Supprime le paquet et la config'],
    [/\bRemoves dependencies\b/gi, 'Supprime les dépendances'],
    [/\bRemoves all related\b/gi, 'Supprime tout ce qui est lié'],
    [/\bSearches package names and descriptions\b/gi, 'Recherche dans les noms et descriptions des paquets'],
    [/\bSearches names only\b/gi, 'Recherche uniquement dans les noms'],
    [/\bSearches installed\b/gi, 'Recherche dans les paquets installés'],
    [/\bSearches repos\b/gi, 'Recherche dans les dépôts'],
    [/\bInstalls package \(RHEL\/Fedora\)\b/gi, 'Installe le paquet (RHEL/Fedora)'],
    [/\bDownloads only\b/gi, 'Télécharge uniquement'],
    [/\bInstalls on Debian\b/gi, 'Installe sur Debian'],
    [/\bInstalls dependencies only\b/gi, 'Installe uniquement les dépendances'],
    [/\bInstalls package via Homebrew \(macOS\/Linux\)\b/gi, 'Installe le paquet via Homebrew (macOS/Linux)'],
    [/\bBrews package\b/gi, 'Prépare le paquet'],
    [/\bInstalls from source\b/gi, 'Installe depuis les sources'],
    [/\bInstalls binary\b/gi, 'Installe le binaire'],
    [/\bInstalls snap package \(sandboxed\)\b/gi, 'Installe un paquet snap (sandboxé)'],
    [/\bInstalls traditional package\b/gi, 'Installe un paquet traditionnel'],
    [/\bSnapshots package\b/gi, 'Crée un snapshot du paquet'],
    [/\bInstalls from snap store\b/gi, 'Installe depuis le Snap store'],
    [/\bInstalls Flatpak application \(sandboxed\)\b/gi, 'Installe une application Flatpak (sandboxée)'],
    [/\bInstalls flat package\b/gi, 'Installe un paquet flat'],
    [/\bInstalls from Flathub\b/gi, 'Installe depuis Flathub'],
    [/\bInstalls flatpak\b/gi, 'Installe Flatpak'],
    [/\bBuilds project using Makefile\b/gi, 'Compile le projet avec le Makefile'],
    [/\bMakes files\b/gi, 'Crée des fichiers'],
    [/\bCompiles C\b/gi, 'Compile du C'],
    [/\bRuns makefile\b/gi, 'Exécute le makefile'],
    [/\bConfigures build for your system before make\b/gi, 'Configure la compilation pour votre système avant make'],
    [/\bConfigures system\b/gi, 'Configure le système'],
    [/\bRuns configuration\b/gi, 'Exécute la configuration'],
    [/\bSets up build\b/gi, 'Prépare la compilation'],
    [/\bSearches package cache \(same as apt search\)\b/gi, 'Recherche dans le cache des paquets (comme apt search)'],
    [/\bSearches cache only\b/gi, 'Recherche uniquement dans le cache'],
    [/\bCaches search\b/gi, 'Met en cache la recherche'],
    [/\bSearches apt cache\b/gi, 'Recherche dans le cache apt'],
    [/\bInstalls \.deb file directly \(no dependency resolution\)\b/gi, 'Installe le fichier .deb directement (sans résolution des dépendances)'],
    [/\bInstalls with deps\b/gi, 'Installe avec les dépendances'],
    [/\bImports package\b/gi, 'Importe le paquet'],
    [/\bList of packages\b/gi, 'Liste des paquets'],
    [/\bPackage list\b/gi, 'Liste des paquets'],
    [/\bInstalled packages\b/gi, 'Paquets installés'],
    // Level 6: Networking
    [/\bSends ICMP echo requests to test connectivity\b/gi, 'Envoie des requêtes ICMP echo pour tester la connectivité'],
    [/\bPings host\b/gi, 'Ping l\'hôte'],
    [/\bTests connection\b/gi, 'Teste la connexion'],
    [/\bChecks host\b/gi, 'Vérifie l\'hôte'],
    [/\bTransfers data from URL \(HTTP, FTP, etc\.\)\b/gi, 'Transfère des données depuis une URL (HTTP, FTP, etc.)'],
    [/\bCurls URL\b/gi, 'Récupère l\'URL'],
    [/\bFetches URL\b/gi, 'Récupère l\'URL'],
    [/\bDownloads URL\b/gi, 'Télécharge l\'URL'],
    [/\bDownloads file from URL\b/gi, 'Télécharge un fichier depuis une URL'],
    [/\bGets web\b/gi, 'Récupère le web'],
    [/\bWeb get\b/gi, 'Récupération web'],
    [/\bDownloads web\b/gi, 'Télécharge le web'],
    [/\bConnects to remote host via SSH\b/gi, 'Se connecte à l\'hôte distant via SSH'],
    [/\bSecure shell\b/gi, 'Shell sécurisé'],
    [/\bSSH connect\b/gi, 'Connexion SSH'],
    [/\bRemote login\b/gi, 'Connexion à distance'],
    [/\bCopies file to remote host over SSH\b/gi, 'Copie le fichier vers l\'hôte distant via SSH'],
    [/\bSecure copy\b/gi, 'Copie sécurisée'],
    [/\bSCP copy\b/gi, 'Copie SCP'],
    [/\bCopies over SSH\b/gi, 'Copie via SSH'],
    [/\bSyncs files \(archive, verbose\)\. Efficient for transfers\b/gi, 'Synchronise les fichiers (archive, verbeux). Efficace pour les transferts'],
    [/\bRsync copy\b/gi, 'Copie rsync'],
    [/\bSyncs src to dest\b/gi, 'Synchronise src vers dest'],
    [/\bArchive sync\b/gi, 'Sync archive'],
    [/\bNumber \(0-65535\) identifying service\/application\b/gi, 'Numéro (0-65535) identifiant le service ou l\'application'],
    [/\bPhysical port\b/gi, 'Port physique'],
    [/\bNetwork port\b/gi, 'Port réseau'],
    [/\bPort number\b/gi, 'Numéro de port'],
    [/\bQueries DNS for domain info\b/gi, 'Interroge le DNS pour les infos du domaine'],
    [/\bName lookup\b/gi, 'Résolution de nom'],
    [/\bDNS lookup\b/gi, 'Requête DNS'],
    [/\bResolves domain\b/gi, 'Résout le domaine'],
    [/\bDNS lookup with detailed output\b/gi, 'Requête DNS avec sortie détaillée'],
    [/\bDig domain\b/gi, 'Requête dig'],
    [/\bDNS query\b/gi, 'Requête DNS'],
    [/\bDomain info\b/gi, 'Infos du domaine'],
    [/\bSimple DNS lookup\b/gi, 'Requête DNS simple'],
    [/\bHost lookup\b/gi, 'Recherche d\'hôte'],
    [/\bDNS host\b/gi, 'Hôte DNS'],
    [/\bNetwork interface configuration \(legacy\)\b/gi, 'Configuration des interfaces réseau (ancien)'],
    [/\bIP config\b/gi, 'Config IP'],
    [/\bInterface config\b/gi, 'Config interface'],
    [/\bNetwork config\b/gi, 'Config réseau'],
    [/\bIP addresses and interface info\b/gi, 'Adresses IP et infos des interfaces'],
    [/\bIP address\b/gi, 'Adresse IP'],
    [/\bAddress list\b/gi, 'Liste d\'adresses'],
    [/\bInterface addresses\b/gi, 'Adresses des interfaces'],
    [/\bListening TCP ports and processes\b/gi, 'Ports TCP en écoute et processus'],
    [/\bNet stat\b/gi, 'Net stat'],
    [/\bPort list\b/gi, 'Liste des ports'],
    [/\bTCP listeners\b/gi, 'Écouteurs TCP'],
    [/\bSocket statistics \(listening TCP, processes\)\b/gi, 'Statistiques des sockets (TCP en écoute, processus)'],
    [/\bSS sockets\b/gi, 'Sockets ss'],
    [/\bSocket list\b/gi, 'Liste des sockets'],
    [/\bTCP sockets\b/gi, 'Sockets TCP'],
    // Level 7: Advanced networking
    [/\bAdds IP address to interface\b/gi, 'Ajoute une adresse IP à l\'interface'],
    [/\bAdds address\b/gi, 'Ajoute une adresse'],
    [/\bAssigns IP\b/gi, 'Assigne l\'IP'],
    [/\bSets IP\b/gi, 'Définit l\'IP'],
    [/\bBrings interface up\b/gi, 'Met l\'interface en service'],
    [/\bEnables interface\b/gi, 'Active l\'interface'],
    [/\bActivates eth0\b/gi, 'Active eth0'],
    [/\bTurns on interface\b/gi, 'Met l\'interface en marche'],
    [/\bAdds default gateway\b/gi, 'Ajoute la passerelle par défaut'],
    [/\bAdds route\b/gi, 'Ajoute une route'],
    [/\bSets gateway\b/gi, 'Définit la passerelle'],
    [/\bDefault route\b/gi, 'Route par défaut'],
    [/\bLists firewall rules\b/gi, 'Liste les règles du pare-feu'],
    [/\bLists iptables\b/gi, 'Liste iptables'],
    [/\bShows rules\b/gi, 'Affiche les règles'],
    [/\bFirewall list\b/gi, 'Liste du pare-feu'],
    [/\bAllows incoming SSH \(port 22\)\b/gi, 'Autorise les connexions SSH entrantes (port 22)'],
    [/\bAccepts TCP 22\b/gi, 'Accepte TCP 22'],
    [/\bAllows port 22\b/gi, 'Autorise le port 22'],
    [/\bSSH rule\b/gi, 'Règle SSH'],
    [/\bSets default policy for INPUT to DROP\b/gi, 'Définit la politique par défaut d\'INPUT sur DROP'],
    [/\bPolicy drop\b/gi, 'Politique DROP'],
    [/\bDefault drop\b/gi, 'DROP par défaut'],
    [/\bINPUT policy\b/gi, 'Politique INPUT'],
    [/\bAll nftables rules\b/gi, 'Toutes les règles nftables'],
    [/\bNft ruleset\b/gi, 'Règles nft'],
    [/\bNftables rules\b/gi, 'Règles nftables'],
    [/\bFirewall rules\b/gi, 'Règles du pare-feu'],
    [/\bCreates bridge interface\b/gi, 'Crée une interface pont'],
    [/\bAdds bridge\b/gi, 'Ajoute un pont'],
    [/\bCreates bridge\b/gi, 'Crée un pont'],
    [/\bBridge interface\b/gi, 'Interface pont'],
    [/\bVirtual LAN \(802\.1Q tagged network\)\b/gi, 'Réseau local virtuel (réseau étiqueté 802.1Q)'],
    [/\bVirtual network\b/gi, 'Réseau virtuel'],
    [/\bVLAN tag\b/gi, 'Étiquette VLAN'],
    [/\bTagged network\b/gi, 'Réseau étiqueté'],
    [/\bCreates VLAN 10 on eth0\b/gi, 'Crée le VLAN 10 sur eth0'],
    [/\bAdds VLAN\b/gi, 'Ajoute un VLAN'],
    [/\bVLAN interface\b/gi, 'Interface VLAN'],
    [/\bCreates tagged interface\b/gi, 'Crée une interface étiquetée'],
    [/\bCaptures packets on port 80\b/gi, 'Capture les paquets sur le port 80'],
    [/\bTcpdump port 80\b/gi, 'Tcpdump port 80'],
    [/\bHTTP capture\b/gi, 'Capture HTTP'],
    [/\bPort 80 capture\b/gi, 'Capture port 80'],
    [/\bEstablished TCP connections\b/gi, 'Connexions TCP établies'],
    [/\bTCP established\b/gi, 'TCP établi'],
    [/\bActive connections\b/gi, 'Connexions actives'],
    [/\bConnected sockets\b/gi, 'Sockets connectés'],
    [/\bConnection tracking table\b/gi, 'Table de suivi des connexions'],
    [/\bConntrack list\b/gi, 'Liste conntrack'],
    [/\bTracked connections\b/gi, 'Connexions suivies'],
    [/\bNAT connections\b/gi, 'Connexions NAT'],
    [/\bNAT table rules\b/gi, 'Règles de la table NAT'],
    [/\bNAT rules\b/gi, 'Règles NAT'],
    [/\bNat table\b/gi, 'Table NAT'],
    [/\bTranslation rules\b/gi, 'Règles de traduction'],
    // Level 8: Security
    [/\bChanges user password\b/gi, 'Change le mot de passe utilisateur'],
    [/\bShows password\b/gi, 'Affiche le mot de passe'],
    [/\bSets password\b/gi, 'Définit le mot de passe'],
    [/\bPassword command\b/gi, 'Commande mot de passe'],
    [/\bCreates new user account\b/gi, 'Crée un nouveau compte utilisateur'],
    [/\bAdds user\b/gi, 'Ajoute un utilisateur'],
    [/\bCreates user\b/gi, 'Crée un utilisateur'],
    [/\bUser add\b/gi, 'Ajout utilisateur'],
    [/\bAdds user to supplementary group\b/gi, 'Ajoute l\'utilisateur à un groupe secondaire'],
    [/\bAdds to group\b/gi, 'Ajoute au groupe'],
    [/\bModifies user\b/gi, 'Modifie l\'utilisateur'],
    [/\bGroup add\b/gi, 'Ajout au groupe'],
    [/\bOwner read\+write only \(rw-------\)\b/gi, 'Propriétaire lecture+écriture uniquement (rw-------)'],
    [/\bRead write only\b/gi, 'Lecture écriture uniquement'],
    [/\b600 permissions\b/gi, 'Permissions 600'],
    [/\bOwner only\b/gi, 'Propriétaire uniquement'],
    [/\bOwner full access, none for others \(rwx------\)\b/gi, 'Propriétaire accès total, aucun pour les autres (rwx------)'],
    [/\bDirectory 700\b/gi, 'Répertoire 700'],
    [/\bOwner only dir\b/gi, 'Répertoire propriétaire uniquement'],
    [/\bPrivate directory\b/gi, 'Répertoire privé'],
    [/\bSafely edits sudoers file\b/gi, 'Modifie le fichier sudoers en toute sécurité'],
    [/\bEdit sudoers\b/gi, 'Éditer sudoers'],
    [/\bSudo config\b/gi, 'Config sudo'],
    [/\bSudoers editor\b/gi, 'Éditeur sudoers'],
    [/\bYour sudo privileges\b/gi, 'Vos privilèges sudo'],
    [/\bSudo list\b/gi, 'Liste sudo'],
    [/\bAllowed commands\b/gi, 'Commandes autorisées'],
    [/\bSudo permissions\b/gi, 'Permissions sudo'],
    [/\bSwitches to user with login shell\b/gi, 'Passe à l\'utilisateur avec shell de connexion'],
    [/\bSwitch user\b/gi, 'Changer d\'utilisateur'],
    [/\bSu login\b/gi, 'Connexion su'],
    [/\bLogin as user\b/gi, 'Se connecter en tant qu\'utilisateur'],
    [/\bUser and group IDs\b/gi, 'UID et GID utilisateur'],
    [/\bUser ID\b/gi, 'UID'],
    [/\bIdentity\b/gi, 'Identité'],
    [/\bUID GID\b/gi, 'UID GID'],
    [/\bLogged-in users\b/gi, 'Utilisateurs connectés'],
    [/\bWho is logged in\b/gi, 'Qui est connecté'],
    [/\bUsers\b/gi, 'Utilisateurs'],
    [/\bSessions\b/gi, 'Sessions'],
    [/\bLogin history\b/gi, 'Historique des connexions'],
    [/\bLast logins\b/gi, 'Dernières connexions'],
    [/\bLogin log\b/gi, 'Journal des connexions'],
    [/\bUser history\b/gi, 'Historique utilisateur'],
    [/\bFailed login attempts\b/gi, 'Tentatives de connexion échouées'],
    [/\bBad logins\b/gi, 'Mauvaises connexions'],
    [/\bFailed logins\b/gi, 'Connexions échouées'],
    [/\bLogin failures\b/gi, 'Échecs de connexion'],
    // Level 9: Pentest
    [/\bProbes open ports for service\/version\b/gi, 'Sonde les ports ouverts pour service/version'],
    [/\bNmap version\b/gi, 'Version nmap'],
    [/\bService detection\b/gi, 'Détection de service'],
    [/\bVersion scan\b/gi, 'Scan de version'],
    [/\bRuns default NSE scripts\b/gi, 'Exécute les scripts NSE par défaut'],
    [/\bNmap scripts\b/gi, 'Scripts nmap'],
    [/\bDefault scripts\b/gi, 'Scripts par défaut'],
    [/\bScript scan\b/gi, 'Scan de scripts'],
    [/\bAttempts OS detection\b/gi, 'Tente la détection de l\'OS'],
    [/\bOS detection\b/gi, 'Détection d\'OS'],
    [/\bNmap OS\b/gi, 'OS nmap'],
    [/\bOperating system\b/gi, 'Système d\'exploitation'],
    [/\bScans all 65535 ports\b/gi, 'Scanne les 65535 ports'],
    [/\bAll ports\b/gi, 'Tous les ports'],
    [/\bFull port scan\b/gi, 'Scan complet des ports'],
    [/\bPort range\b/gi, 'Plage de ports'],
    [/\bSYN scan \(half-open, stealthier\)\b/gi, 'Scan SYN (demi-ouvert, plus furtif)'],
    [/\bSYN scan\b/gi, 'Scan SYN'],
    [/\bStealth scan\b/gi, 'Scan furtif'],
    [/\bHalf-open scan\b/gi, 'Scan demi-ouvert'],
    [/\bUDP scan on DNS and SNMP ports\b/gi, 'Scan UDP sur les ports DNS et SNMP'],
    [/\bUDP scan\b/gi, 'Scan UDP'],
    [/\bUDP ports\b/gi, 'Ports UDP'],
    [/\bUDP probe\b/gi, 'Sonde UDP'],
    [/\bRuns vulnerability detection scripts\b/gi, 'Exécute les scripts de détection de vulnérabilités'],
    [/\bVuln scripts\b/gi, 'Scripts vuln'],
    [/\bVulnerability scan\b/gi, 'Scan de vulnérabilités'],
    [/\bNSE vuln\b/gi, 'NSE vuln'],
    [/\bWeb server vulnerability scanner\b/gi, 'Scanner de vulnérabilités serveur web'],
    [/\bNikto scan\b/gi, 'Scan nikto'],
    [/\bWeb vuln scan\b/gi, 'Scan vuln web'],
    [/\bHTTP scanner\b/gi, 'Scanner HTTP'],
    [/\bDirectory\/file brute force\b/gi, 'Brute force répertoires/fichiers'],
    [/\bGobuster dir\b/gi, 'Gobuster dir'],
    [/\bDirectory bust\b/gi, 'Directory bust'],
    [/\bWordlist dir\b/gi, 'Répertoire wordlist'],
    [/\bSubdomain enumeration\b/gi, 'Énumération des sous-domaines'],
    [/\bGobuster DNS\b/gi, 'Gobuster DNS'],
    [/\bSubdomain brute\b/gi, 'Brute force sous-domaines'],
    [/\bDNS brute\b/gi, 'Brute force DNS'],
    [/\bSearches Exploit-DB for exploits\b/gi, 'Recherche des exploits dans Exploit-DB'],
    [/\bSearch exploit\b/gi, 'Recherche d\'exploit'],
    [/\bExploit search\b/gi, 'Recherche d\'exploit'],
    [/\bExploit DB\b/gi, 'Exploit-DB'],
    [/\bMetasploit Framework console\b/gi, 'Console Metasploit Framework'],
    [/\bMetasploit\b/gi, 'Metasploit'],
    [/\bMSF console\b/gi, 'Console MSF'],
    [/\bExploit framework\b/gi, 'Framework d\'exploitation'],
    // Level 10: Docker, Git
    [/\bRuns nginx container\b/gi, 'Lance le conteneur nginx'],
    [/\bDocker run\b/gi, 'Docker run'],
    [/\bStart container\b/gi, 'Démarrer le conteneur'],
    [/\bRun nginx\b/gi, 'Lancer nginx'],
    [/\bRunning containers\b/gi, 'Conteneurs en cours d\'exécution'],
    [/\bDocker list\b/gi, 'Liste docker'],
    [/\bContainers\b/gi, 'Conteneurs'],
    [/\bBuilds image from Dockerfile in current dir\b/gi, 'Construit l\'image depuis le Dockerfile du répertoire courant'],
    [/\bDocker build\b/gi, 'Docker build'],
    [/\bBuild image\b/gi, 'Construire l\'image'],
    [/\bCreate image\b/gi, 'Créer l\'image'],
    [/\bRuns bash in running container\b/gi, 'Lance bash dans le conteneur en cours'],
    [/\bDocker exec\b/gi, 'Docker exec'],
    [/\bExec in container\b/gi, 'Exécuter dans le conteneur'],
    [/\bContainer shell\b/gi, 'Shell du conteneur'],
    [/\bStops container \(SIGTERM then SIGKILL\)\b/gi, 'Arrête le conteneur (SIGTERM puis SIGKILL)'],
    [/\bDocker stop\b/gi, 'Docker stop'],
    [/\bStop container\b/gi, 'Arrêter le conteneur'],
    [/\bHalt container\b/gi, 'Stopper le conteneur'],
    [/\bRemoves stopped container\b/gi, 'Supprime le conteneur arrêté'],
    [/\bDocker rm\b/gi, 'Docker rm'],
    [/\bRemove container\b/gi, 'Supprimer le conteneur'],
    [/\bDelete container\b/gi, 'Supprimer le conteneur'],
    [/\bList of images\b/gi, 'Liste des images'],
    [/\bDocker images\b/gi, 'Docker images'],
    [/\bImage list\b/gi, 'Liste des images'],
    [/\bBuilt images\b/gi, 'Images construites'],
    [/\bDownloads image from registry\b/gi, 'Télécharge l\'image depuis le registre'],
    [/\bDocker pull\b/gi, 'Docker pull'],
    [/\bPull image\b/gi, 'Télécharger l\'image'],
    [/\bDownload image\b/gi, 'Télécharger l\'image'],
    [/\bMaps host 8080 to container 80\b/gi, 'Mappe l\'hôte 8080 vers le conteneur 80'],
    [/\bPort map\b/gi, 'Mappage de port'],
    [/\bPublish port\b/gi, 'Publier le port'],
    [/\bPort forward\b/gi, 'Redirection de port'],
    [/\bMounts host directory into container\b/gi, 'Monte le répertoire hôte dans le conteneur'],
    [/\bVolume mount\b/gi, 'Montage de volume'],
    [/\bBind mount\b/gi, 'Montage lié'],
    [/\bMount volume\b/gi, 'Monter le volume'],
    [/\bCreates new Git repository\b/gi, 'Crée un nouveau dépôt Git'],
    [/\bGit init\b/gi, 'Git init'],
    [/\bInit repo\b/gi, 'Init dépôt'],
    [/\bNew repository\b/gi, 'Nouveau dépôt'],
    [/\bClones remote repository\b/gi, 'Clone le dépôt distant'],
    [/\bGit clone\b/gi, 'Git clone'],
    [/\bClone repo\b/gi, 'Cloner le dépôt'],
    [/\bCopy repository\b/gi, 'Copier le dépôt'],
  ];

  let result = text;
  for (const [pattern, replacement] of optionTranslations) {
    result = result.replace(pattern, replacement);
  }

  // Fallback: word-level translation so ALL option text ends up in French (no English left)
  const wordMap: Record<string, string> = {
    the: 'le', The: 'Le', a: 'un', A: 'Un', an: 'un', An: 'Un',
    of: 'de', to: 'à', in: 'dans', for: 'pour', on: 'sur', with: 'avec', at: 'à', from: 'de', by: 'par',
    or: 'ou', and: 'et', but: 'mais', only: 'seulement', just: 'juste', both: 'les deux', each: 'chaque',
    all: 'tous', some: 'certains', any: 'tout', no: 'aucun', not: 'pas', same: 'même', other: 'autre',
    one: 'un', first: 'premier', last: 'dernier', next: 'suivant', current: 'courant', new: 'nouveau',
    running: 'en cours', stopped: 'arrêté', created: 'créé', deleted: 'supprimé', removed: 'supprimé',
    added: 'ajouté', updated: 'mis à jour', saved: 'enregistré', show: 'affiche',
    display: 'affiche', print: 'affiche', run: 'exécute', start: 'démarre', stop: 'arrête',
    close: 'ferme', file: 'fichier', files: 'fichiers', directory: 'répertoire',
    directories: 'répertoires', folder: 'dossier', folders: 'dossiers', command: 'commande',
    commands: 'commandes', process: 'processus', processes: 'processus', user: 'utilisateur',
    group: 'groupe', system: 'système', contents: 'contenu', content: 'contenu',
    path: 'chemin', paths: 'chemins', name: 'nom', names: 'noms', output: 'sortie', input: 'entrée',
    error: 'erreur', message: 'message', window: 'fenêtre', text: 'texte', line: 'ligne', key: 'touche',
    click: 'clic', type: 'type', data: 'données', image: 'image', images: 'images',
    package: 'paquet', packages: 'paquets', install: 'installe', installs: 'installe',
    remove: 'supprime', removes: 'supprime', download: 'télécharge', downloads: 'télécharge',
    copy: 'copie', copies: 'copie', move: 'déplace', moves: 'déplace', create: 'crée', creates: 'crée',
    change: 'change', changes: 'change', set: 'définit', sets: 'définit', get: 'obtient', gets: 'obtient',
    read: 'lecture', write: 'écriture', full: 'complet', access: 'accès', none: 'aucun',
    owner: 'propriétaire', others: 'autres', default: 'par défaut', policy: 'politique',
    rule: 'règle', rules: 'règles', table: 'table', connection: 'connexion', connections: 'connexions',
    port: 'port', ports: 'ports', address: 'adresse', addresses: 'adresses', interface: 'interface',
    network: 'réseau', host: 'hôte', remote: 'distant', local: 'local', container: 'conteneur',
    containers: 'conteneurs', repository: 'dépôt', repositories: 'dépôts', clone: 'clone', clones: 'clone',
    build: 'construit', builds: 'construit', pull: 'télécharge', mount: 'monte', mounts: 'monte',
    volume: 'volume', volumes: 'volumes', scan: 'scan', scans: 'scanne', detection: 'détection',
    version: 'version', script: 'script', scripts: 'scripts', exploit: 'exploit', exploits: 'exploits',
    vulnerability: 'vulnérabilité', vulnerabilities: 'vulnérabilités', server: 'serveur',
    web: 'web', brute: 'brute', force: 'force', enumeration: 'énumération', subdomain: 'sous-domaine',
    subdomains: 'sous-domaines', login: 'connexion', logins: 'connexions', history: 'historique',
    failed: 'échouées', 'logged-in': 'connectés', password: 'mot de passe',
    privileges: 'privilèges', safely: 'en toute sécurité', edits: 'modifie', switches: 'passe',
    supplementary: 'secondaire', snapshot: 'instantané', interactive: 'interactif',
    'real-time': 'temps réel', monitor: 'moniteur', sends: 'envoie', send: 'envoie',
    'force-kills': 'tue de force', scheduling: 'ordonnancement', priority: 'priorité',
    value: 'valeur', values: 'valeurs', jobs: 'tâches', job: 'tâche', background: 'arrière-plan',
    terminal: 'terminal', service: 'service', services: 'services', load: 'charge',
    averages: 'moyennes', memory: 'mémoire', swap: 'swap', usage: 'utilisation', disk: 'disque',
    space: 'espace', virtual: 'virtuel', finds: 'trouve', find: 'trouve', matching: 'correspondant',
    suspended: 'suspendues', shell: 'shell', refreshes: 'met à jour',
    index: 'index', upgrades: 'met à jour', installed: 'installés', latest: 'dernières',
    versions: 'versions', dependencies: 'dépendances', keeps: 'garde', config: 'config',
    searches: 'recherche', descriptions: 'descriptions', via: 'via', sandboxed: 'sandboxé',
    project: 'projet', using: 'utilisant', directly: 'directement', resolution: 'résolution',
    'human-readable': 'lisible', transfers: 'transfère', connectivity: 'connectivité',
    syncs: 'synchronise', efficient: 'efficace', number: 'numéro', identifying: 'identifiant',
    application: 'application', queries: 'interroge', detailed: 'détails', configuration: 'configuration',
    legacy: 'ancien', listening: 'en écoute', statistics: 'statistiques', sockets: 'sockets',
    adds: 'ajoute', brings: 'met', gateway: 'passerelle', firewall: 'pare-feu', allows: 'autorise',
    incoming: 'entrantes', bridge: 'pont', tagged: 'étiqueté', captures: 'capture',
    packets: 'paquets', established: 'établies', tracking: 'suivi', translation: 'traduction',
    account: 'compte', probes: 'sonde', runs: 'exécute',
    scanner: 'scanner', registry: 'registre', maps: 'mappe', Yes: 'Oui', No: 'Non',
    Data: 'Données', blinking: 'clignotant', appears: 'apparaît', where: 'où', place: 'endroit',
    before: 'avant', mouse: 'souris', pointer: 'pointeur', title: 'titre', working: 'travail',
    cable: 'câble', keyboard: 'clavier',
    recognize: 'reconnaît', typed: 'tapé', worked: 'réussi', need: 'besoin', press: 'appuyez',
    Enter: 'Entrée', Return: 'Retour', Space: 'Espace', Escape: 'Échap', Tab: 'Tab',
    computer: 'ordinateur', desktop: 'bureau', taskbar: 'barre des tâches', 'menu bar': 'barre de menus',
    temporary: 'temporaire', main: 'principal', personal: 'personnel',
    location: 'emplacement', inside: 'dedans', bigger: 'plus grand', empty: 'vide',
    successful: 'réussi', result: 'résultat', closed: 'fermée',
    programming: 'programmation', language: 'langage', graphical: 'graphique', icons: 'icônes',
    clicks: 'clics', capitals: 'majuscules', different: 'différentes',
    mistake: 'faute', typing: 'frappe', character: 'caractère', saying: 'indiquant',
    went: 'est', wrong: 'mal', supposed: 'devait', pressed: 'appuyé',
    single: 'seul', software: 'logiciel', specific: 'spécifique',
    edit: 'éditer', Formatted: 'Formaté', permissions: 'permissions',
    details: 'détails', hidden: 'cachés', dotfiles: 'fichiers point', recursive: 'récursif',
    reverse: 'inverse', order: 'ordre', word: 'mot', HOME: 'HOME', count: 'nombre',
    stay: 'reste', arguments: 'arguments', wildcard: 'joker',
    string: 'chaîne', characters: 'caractères', digit: 'chiffre', digits: 'chiffres',
    letter: 'lettre', letters: 'lettres', status: 'statut', format: 'format', long: 'long', match: 'correspond',
    executable: 'exécutable', executables: 'exécutables', recent: 'récent', renames: 'renomme',
    catalogs: 'catalogue', forward: 'avant', difference: 'différence',
    bytes: 'octets', byte: 'octet', words: 'mots', column: 'colonne',
    open: 'ouverts', attempts: 'tente', documents: 'documents', printed: 'affiché',
    document: 'document', list: 'liste',
    comma: 'virgule', delimited: 'séparé', merges: 'fusionne', side: 'côte', vertically: 'verticalement',
    compares: 'compare', clipboard: 'presse-papiers', translates: 'traduit', lowercase: 'minuscules',
    uppercase: 'majuscules', transposes: 'transpose', replaces: 'remplace', trims: 'supprime',
    appends: 'ajoute', reads: 'lit', pipe: 'tube', writes: 'écrit', stdin: 'entrée standard',
    stdout: 'sortie standard',
  };
  for (const [en, fr] of Object.entries(wordMap)) {
    const esc = en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const re = new RegExp(`\\b${esc}\\b`, 'gi');
    result = result.replace(re, (match) => (match[0] === match[0].toUpperCase() ? fr.charAt(0).toUpperCase() + fr.slice(1) : fr));
  }

  // Final fallback for any natural-language option text still containing common English words.
  // This keeps A/B/C/D choices in French mode even when a phrase was not covered above.
  if (
    /\b(the|a|an|and|or|with|without|for|from|to|of|what|which|show|shows|list|create|delete|copy|move|running|current|directory|file|command|output|error|user|system)\b/i.test(result) &&
    /[A-Za-z]/.test(result)
  ) {
    result = translateQuestionText(result, 'fr');
  }

  return sanitizeFrenchArtifacts(result);
};

const sanitizeFrenchArtifacts = (text: string): string => {
  let out = replaceFallacyNamesInText(text);

  const artifactReplacements: Array<[RegExp, string]> = [
    [/\bis[\-‐‑–—]ought\b/gi, 'est-devoir'],
    [/\bis\s+un\b/gi, 'est un'],
    [/\bis\s+une\b/gi, 'est une'],
    [/\bTHIS CONCEPT\b/g, 'ce concept'],
    [/\bthis concept\b/gi, 'ce concept'],
    [/\bThe\s+(un|une)\b/gi, '$1'],
    [/\bIf-By-?\b/gi, ''],
    [/\bfallacy\b/gi, 'sophisme'],
    [/\bbias\b/gi, 'biais'],
    [/\boverwriting\b/gi, 'écrasement'],
    [/\boverwrites\b/gi, 'écrase'],
    [/\boverwrite\b/gi, 'écraser'],
    [/\bholds\b/gi, 'contient'],
    [/\bkeep going\b/gi, 'continuez'],
    [/\bwhere you left off\b/gi, 'là où vous vous êtes arrêté'],
    [/\bwhere you stopped\b/gi, 'là où vous vous êtes arrêté'],
    [/\bde où you arrêté\b/gi, 'là où vous vous êtes arrêté'],
    [/\bnext question\b/gi, 'question suivante'],
    [/\bsame level\b/gi, 'même niveau'],
    [/\byou\b/gi, 'vous'],
    [/\byour\b/gi, 'votre'],
    [/\bby un raisonnement\b/gi, 'par un raisonnement'],
    [/\bby une\b/gi, 'par une'],
    [/\bof un\b/gi, "d'un"],
    [/\bof une\b/gi, "d'une"],
    [/\bof the\b/gi, 'du'],
  ];

  for (const [pattern, replacement] of artifactReplacements) {
    out = out.replace(pattern, replacement);
  }

  return out;
};

/** Strip "Identify the logical fallacy in this example..." / "Identifiez l'erreur logique..." prefix and optional surrounding quotes. */
export const stripFallacyInstructionPrefix = (q: string): string => {
  const enPrefix = /^Identify the logical fallacy in this example:\s*\n*\s*/i;
  const frPrefixSophisme = /^Identifiez le sophisme (?:logique )?dans cet exemple\s*:\s*\n*\s*/i;
  const frPrefixErreur = /^Identifiez l'erreur logique dans cet exemple\s*:\s*\n*\s*/i;
  let rest = q.replace(enPrefix, '').replace(frPrefixSophisme, '').replace(frPrefixErreur, '').trim();
  if (rest.length >= 2 && rest.startsWith('"') && rest.endsWith('"')) {
    rest = rest.slice(1, -1).trim();
  }
  return rest || q;
};

/**
 * Returns question and options in the requested language. When language is 'fr',
 * translates question and each option to French so the entire logic/quiz panel is in French.
 * For logical fallacy questions, the "Identify the logical fallacy in this example..." prefix
 * is stripped so only the example argument is shown.
 */
/**
 * When the loaded question bank already matches the UI language (native EN or FR),
 * use this — no EN→FR translation pass (avoids mangling French bank text).
 */
export const getQuestionDisplayNativeBank = (
  question: string,
  options: string[]
): { question: string; options: string[] } => {
  const questionOnly = stripFallacyInstructionPrefix(question);
  return { question: questionOnly, options };
};

export const getQuestionDisplay = (
  language: string,
  question: string,
  options: string[]
): { question: string; options: string[] } => {
  const questionOnly = stripFallacyInstructionPrefix(question);
  if (language !== 'fr') {
    return { question: questionOnly, options };
  }
  return {
    question: translateQuestionText(questionOnly, 'fr'),
    options: options.map((opt) => translateOptionText(opt, 'fr')),
  };
};
